# backend/Dockerfile.backend

FROM python:buster
COPY requirements.txt /tmp/
CMD pip install -U pip
RUN pip install -r /tmp/requirements.txt
ADD ./backend /code
WORKDIR /code
CMD gunicorn -w 1 -b 0.0.0.0:4001 --worker-class gevent backend.server:app
